import Header from "./header/Header"
import Arrow from "./svg/Arrow"
import DashboardIcon from "./svg/DashboardIcon"
import ProtectedRouted from "./ProtectedRoutes/ProtectedRoutes"
import Dashboard from "./dashboard/Dashboard"
import Login from "./login/Login"
import useFetchData from "../hooks/useFetchData"
import SubMenu from "./dashboard/SubMenu"
import SideBar from "./dashboard/SideBar"
import HomeIcon from "./svg/HomeIcon"
import LogoutIcon from "./svg/LogoutIcon"
import Menu from "../components/dashboard/Menu"
import Close from "./svg/Close"
import Main from "./dashboard/Main"
import ListIcon from "./svg/ListIcon"
import UserIcon from "./svg/UserIcon"
import DashboardHeader from "./dashboard/DashboardHeader"
import ProductList from "./dashboard/ProductList"
import Trash from "./svg/Trash"
import Plus from "./svg/Plus"
import EditIcon from "./svg/EditIcon"
import NewProduct from "./dashboard/NewProduct"
import Pagination from "./dashboard/Pagination"

export { Header }
export { Arrow }
export { DashboardIcon }
export { ProtectedRouted }
export { Dashboard }
export { Login }
export { useFetchData }
export { SubMenu }
export { SideBar }
export { HomeIcon }
export { LogoutIcon }
export { Menu }
export { Close }
export { Main }
export { ListIcon }
export { UserIcon }
export { DashboardHeader }
export { ProductList }
export { Trash }
export { Plus }
export { EditIcon }
export { NewProduct }
export { Pagination }